name: Deploy Float and Friends

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use an LTS version of Node.js

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          CI: false
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          github_token: ${{ secrets.FNF_TOKEN }}
